"""update

Revision ID: 6599928aeaad
Revises: f437d961704b
Create Date: 2025-08-12 16:12:21.088133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6599928aeaad"
down_revision: Union[str, Sequence[str], None] = "f437d961704b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("model", sa.String(length=100), nullable=True))
    op.add_column("messages", sa.Column("prompt_tokens", sa.Integer(), nullable=True))
    op.add_column(
        "messages", sa.Column("completion_tokens", sa.Integer(), nullable=True)
    )
    op.add_column("messages", sa.Column("total_tokens", sa.Integer(), nullable=True))
    op.add_column(
        "messages", sa.Column("finish_reason", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "messages",
        "content",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="content::json",
    )
    op.create_foreign_key(
        None, "messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.alter_column(
        "messages",
        "content",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("messages", "finish_reason")
    op.drop_column("messages", "total_tokens")
    op.drop_column("messages", "completion_tokens")
    op.drop_column("messages", "prompt_tokens")
    op.drop_column("messages", "model")
    # ### end Alembic commands ###
